name: Tests

on: [push]

env:
  NODE_VERSION: 10.x

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout master
          uses: actions/checkout@master
        - name: Setup Node.js
          uses: actions/setup-node@v1.1.0
          with:
              version: 10.x
        - name: Run tests
          run: npm run test:unit
